config/routes.rb
PrdcRor::Application.routes.draw do
  
  resources :speakers
  resources :conferences
  resources :events
  resources :sponsors, :only => [:index]
  
  get 'last_update' => "conferences#last_update"
  
  resources :sessions do
    collection do 
      get 'attendance'
    end
    
    member do
      post 'attending', as: 'planning_to_attend'
      post 'not_attending', as: 'planning_not_to_attend'
    end
  end

  resource :schedule, :only => [:show, :edit], :controller => :schedule
  
  match "/schedule/days/:id" => "schedule#days"
  
  
  resources :accounts, :only => :create
  get  "log_in"  => "accounts#new"    
  get  "log_out" => "accounts#destroy"
      
  match "admin" => 'conferences#index'

  #disabled temporarily as we figure out how best to serve pdfs from heroku
  #match 'files/:file_name.:file_format' => 'files#download'

  post 'west' => 'info_requests#create', :as => 'info_requests'

  get 'reports/info' => 'reports#info', :as => 'report_info'

  # catch all simple /:id routes that have not previously
  #   matched and route them through the high_voltage 
  #   pages controller
  match ':id' => 'pages#show', as: 'page'
  
  root :to => 'pages#show', :defaults => {:id => 'home'}
  
  # any error in routing goes to the home
  match '*a', :to => 'pages#home'
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :speakers
  has_many :sessions
  has_many :rooms
  has_many :events
  has_many :sponsors
  
  def days
    (start..finish).to_a
  end
  
  def events_for(day)
    return events.select { |e| e.start.to_date == day }.sort_by { |e| e.start } if day.kind_of? Date
    events_for(days[day - 1]) rescue []
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_filter :authenticate_user!, except: [:last_update]
  layout 'admin'
  
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /admin/conferences/new
  # GET /admin/conferences/new.json
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  def edit
    @conference = Conference.find(params[:id])
  end

  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/conferences/1
  # PUT /admin/conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    Rails.logger.debug { params[:conference] }
    
    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/conferences/1
  # DELETE /admin/conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :ok }
    end
  end
  
  def last_update
    json = { last_update: ConferenceStatus.last_update }.to_json
    respond_to do |format|
      format.json { render json: json }
      format.js   { render json: json, :callback => params[:callback] }
    end
  end
  
end

app/helpers/conferences_helper.rb
module ConferencesHelper

  def format_days(conf = @conference)
    return "" unless conf.start && conf.finish
    head = conf.days[0..-2].map { |d| d.day }.join(', ')
    month = conf.days.first.strftime("%B")
    year = conf.days.first.year
    "#{month} #{head} & #{conf.days.last.day} #{year}"
  end
  
  def format_start(date) 
    date.strftime('%b %e, %Y') if date
  end

  def format_finish(date)
    format_start(date)
  end
  
  def format_active(active)
    active ? "active" : ""
  end
end

app/views/conferences/_form.html.haml
= simple_form_for @conference do |f|
  = f.error_notification

  .inputs
    .field
      = f.input :name
    .field
      = f.input :start, :value => format_start(@conference.start)
    .field
      = f.input :finish, :value => format_finish(@conference.finish)
    .field
      = f.input :active, :value => format_active(@conference.active)
    .field
      = f.input :subdomain
    .field
      = f.input :venue
    .field
      = f.input :city
  .actions
    = f.submit 'Save Conference'

app/views/conferences/edit.html.haml
#conference

  %h1 Editing Conference
  
  = render 'form'
  
  = link_to 'Show', @conference
  \|
  = link_to 'Back', conferences_path

app/views/conferences/index.html.haml
#conferences
  %h1 Listing Conferences
  
  %table{ id: 'list' }
    %tr
      %th Name
      %th Start
      %th Finish
      %th Is Active?
      %th Subdomain
      %th Venue
      %th City
      %th
      %th
      %th
  
    - @conferences.each do |conference|
      %tr
        %td= conference.name
        %td= format_start(conference.start)
        %td= format_finish(conference.finish)
        %td= format_active(conference.active)
        %td= conference.subdomain
        %td= conference.venue
        %td= conference.city
        %td= link_to 'Show', conference
        %td= link_to 'Edit', edit_conference_path(conference)
        %td= button_to("Delete Conference", { :action => "destroy", :id => conference.id }, {:confirm => "Are you sure?", :method => :delete})
  
  %br
  
  = link_to 'New Conference', new_conference_path

app/views/conferences/new.html.haml
.IntContentBox
  .IntContentBoxInfo

    %h1 New Conference
    
    = render 'form'
    
    = link_to 'Back', conferences_path

app/views/conferences/show.html.haml
.IntContentBox
  .IntContentBoxInfo

    %p#notice= notice
    
    = link_to 'Edit', conference_path(@conference)
    \|
    = link_to 'Back', conferences_path