config/routes.rb
PrdcRor::Application.routes.draw do
  
  resources :speakers
  resources :conferences
  resources :events
  resources :sponsors, :only => [:index]
  
  get 'last_update' => "conferences#last_update"
  
  resources :sessions do
    collection do 
      get 'attendance'
    end
    
    member do
      post 'attending', as: 'planning_to_attend'
      post 'not_attending', as: 'planning_not_to_attend'
    end
  end

  resource :schedule, :only => [:show, :edit], :controller => :schedule
  
  match "/schedule/days/:id" => "schedule#days"
  
  
  resources :accounts, :only => :create
  get  "log_in"  => "accounts#new"    
  get  "log_out" => "accounts#destroy"
      
  match "admin" => 'conferences#index'

  #disabled temporarily as we figure out how best to serve pdfs from heroku
  #match 'files/:file_name.:file_format' => 'files#download'

  post 'west' => 'info_requests#create', :as => 'info_requests'

  get 'reports/info' => 'reports#info', :as => 'report_info'

  # catch all simple /:id routes that have not previously
  #   matched and route them through the high_voltage 
  #   pages controller
  match ':id' => 'pages#show', as: 'page'
  
  root :to => 'pages#show', :defaults => {:id => 'home'}
  
  # any error in routing goes to the home
  match '*a', :to => 'pages#home'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :session
  belongs_to :room
  belongs_to :conference
  
  def slot
    TimeSlot.new(start: self.start, finish: self.finish)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_event, only: [:edit, :show, :update, :destroy]
  layout "admin"
  
  def index
    @events = active_conference.events.order(:start)
  end
  
  def edit
    find_sessions
  end
  
  def show
  end
  
  def new
    start = params[:date] || active_conference.start
    @event = Event.new(start: start, finish: start)
    find_sessions
  end
  
  def update
    if @event.update_attributes(params[:event])
      update_session
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render action: "edit"
    end
  end
  
  def destroy
    @event.destroy
    redirect_to events_path
  end
  
  def create
    @event = active_conference.events.create(params[:event])
    update_session
    redirect_to @event, notice: 'Event was successfully created.'
  end

  private
    def find_event
      @event = Event.find(params[:id])
    end

    def find_sessions
      @sessions = active_conference.sessions.order(:title)
    end
    
    def update_session
      session_id = params[:session][:id] rescue ''
      @event.session = Session.find(session_id) unless session_id == ''
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  = f.error_notification

  - session_id = @event.session ? @event.session.id : nil
  
  .inputs
    = f.input :start, :value => @event.start
    = f.input :finish, :value => @event.finish
    = f.association :room, :value => @event.room, prompt: "No Room"
    = f.input :main, :value => @event.main
    = f.input :custom, :value => @event.custom
    %div{class: 'input text optional'}
      = f.label :session, class: 'text'
      = select("session", "id", 
                @sessions.map { |p| [p.title, p.id] }, 
                { include_blank: true, selected: session_id})

  .actions
    = f.button :submit

app/views/events/edit.html.haml
#event

  %h1 Editing event
  
  = render 'form'
  
  = link_to 'Cancel', events_path

app/views/events/index.html.haml
#events

  %h1 Events Administration

  %img.hr{:src=>image_path('pix.gif')}

  -active_conference.days.each do |day|
    - events = @events.select { |e| e.start.to_date == day }
  
    %table.day
      %header
        %span= day.strftime('%b %d %Y')
        = ":"
        = link_to "Add Event", new_event_path(date: day)
        
      %thead
        %th Slot
        %th Session
        %th Room
        %th Main
        %th Custom
        %th
        %th

      - events.each do |e|
        %tr.event
          %td= format_slot(e)
          %td= e.session.title if e.session
          %td= e.room.name if e.room
          %td= e.main ? 'Y' : 'N'
          %td= e.custom
          %td= link_to 'Edit', edit_event_path(e)
          %td= button_to("Delete Event", { :action => "destroy", :id => e.id }, {:confirm => "Are you sure?", :method => :delete})

    

app/views/events/new.html.haml
#event

  %h1 Adding new event
  
  = render 'form'
  
  = link_to 'Cancel', events_path

app/views/events/show.html.haml
#event.IntContentBox
  .IntContentBoxInfo

    %h1 Event information
    
    .field
      Starts:
      = @event.start.strftime('%b %d %Y, %I:%M')
    .field
      Finish:
      = @event.finish.strftime('%b %d %Y, %I:%M')
    .field
      Custom message:
      = @event.custom
    .field
      Main event?
      = @event.main
    .field
      Room:
      = @event.room.name
    .field
      Session:
      = @event.session.title if @event.session
    
    = link_to 'Back to listing', events_path