config/routes.rb
PrdcRor::Application.routes.draw do
  
  resources :speakers
  resources :conferences
  resources :events
  resources :sponsors, :only => [:index]
  
  get 'last_update' => "conferences#last_update"
  
  resources :sessions do
    collection do 
      get 'attendance'
    end
    
    member do
      post 'attending', as: 'planning_to_attend'
      post 'not_attending', as: 'planning_not_to_attend'
    end
  end

  resource :schedule, :only => [:show, :edit], :controller => :schedule
  
  match "/schedule/days/:id" => "schedule#days"
  
  
  resources :accounts, :only => :create
  get  "log_in"  => "accounts#new"    
  get  "log_out" => "accounts#destroy"
      
  match "admin" => 'conferences#index'

  #disabled temporarily as we figure out how best to serve pdfs from heroku
  #match 'files/:file_name.:file_format' => 'files#download'

  post 'west' => 'info_requests#create', :as => 'info_requests'

  get 'reports/info' => 'reports#info', :as => 'report_info'

  # catch all simple /:id routes that have not previously
  #   matched and route them through the high_voltage 
  #   pages controller
  match ':id' => 'pages#show', as: 'page'
  
  root :to => 'pages#show', :defaults => {:id => 'home'}
  
  # any error in routing goes to the home
  match '*a', :to => 'pages#home'
end

app/views/pages/develop.html.haml
#develop.content
  .page-header 
    %h1 API Development

  #documentation.fill
    %h1 Documentation for Developers

    %p Most pages on this site expose read-only data feeds that you can use to build your own third-party applications.

    %p Currently, these feeds are available in JSON and JSONP.

    %h2 What is JSON?

    %p
      %a{:href=>"http://www.json.org/"} JSON
      stands for JavaScript Object Notation and is a lightweight data-interchange format.

    %h3 What Feeds are Available?

    %p To access the following feeds, you must make a request that accepts 'application/JSON' as a response.

    %p 
      Also u can use the extension ".json" in the request to indicate the format desired. 
      Please look at the links below (you may want to install a JSON display plugin).

    %dl#feeds-list
      %dt= "Who is speaking at #{@conference.name}?"
      %dd= link_to "/speakers.json", speakers_path + '.json' 
      %dt What sessions are available?
      %dd= link_to "/sessions.json", sessions_path + '.json' 
      %dt What are the sponsors of the conference?
      %dd= link_to "/sponsors.json", sponsors_path + '.json' 
      %dt What is the schedule of the conference?
      %dd= link_to "/schedule.json", schedule_path + '.json' 
      %dt When was the last time the conference data was modified?
      %dd= link_to "/last_update.json", last_update_path + '.json' 
  
    %h1 Examples

    %p Don't know how to start? Check the examples!

    %dl#examples-list
      %dd= link_to "C#, ASP.NET MVC", "https://github.com/amirci/prdc_api_demo", target: "_blank"
      %dd= link_to "Ruby", "https://gist.github.com/974365", target: "_blank"
      %dd= link_to "Sencha Touch 2", "https://github.com/MonsterCoder/PrdcSencha", target: "_blank"
      %dd= link_to "Windows Phone", "https://github.com/MisterJames/Open-Conference", target: "_blank"

app/views/pages/home.html.haml
.hero-unit
  %h1
    Welcome to the 
    %em= @conference.name
    conference!
    
  %p
    This is a very cool conference to attend!!!
    
.row
  .span6
    %h2 Latest news
    %ul
      %li New sponsorship announced!
      %li Best speaker line-up ever!

  .span5
    %h2 About our sponsors
    %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.

  .span5
    %h2 New venue!
    %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>