config/routes.rb
PrdcRor::Application.routes.draw do
  
  resources :speakers
  resources :conferences
  resources :events
  resources :sponsors, :only => [:index]
  
  get 'last_update' => "conferences#last_update"
  
  resources :sessions do
    collection do 
      get 'attendance'
    end
    
    member do
      post 'attending', as: 'planning_to_attend'
      post 'not_attending', as: 'planning_not_to_attend'
    end
  end

  resource :schedule, :only => [:show, :edit], :controller => :schedule
  
  match "/schedule/days/:id" => "schedule#days"
  
  
  resources :accounts, :only => :create
  get  "log_in"  => "accounts#new"    
  get  "log_out" => "accounts#destroy"
      
  match "admin" => 'conferences#index'

  #disabled temporarily as we figure out how best to serve pdfs from heroku
  #match 'files/:file_name.:file_format' => 'files#download'

  post 'west' => 'info_requests#create', :as => 'info_requests'

  get 'reports/info' => 'reports#info', :as => 'report_info'

  # catch all simple /:id routes that have not previously
  #   matched and route them through the high_voltage 
  #   pages controller
  match ':id' => 'pages#show', as: 'page'
  
  root :to => 'pages#show', :defaults => {:id => 'home'}
  
  # any error in routing goes to the home
  match '*a', :to => 'pages#home'
end

app/views/layouts/admin.html.haml
%html
  %head
    %meta{'http-equiv'=>"Content-Type", :content=>"text/html; charset=UTF-8"}
    %title COnference
    %meta{:name=>"title", :content=>"Conference"}
    %meta{:name=>"keywords", :content=>""}
    %meta{:name=>"description", :content=>""}
    %meta{:name=>"copyright", :content=>"Conference"}
    %meta{:name=>"revisit-after", :content=>"15 days"}

    %meta{:name=>"robots", :content=>"all"}
    = admin_stylesheet
    = csrf_meta_tags
    = yield :dochead

    %body
      %header
        %hgroup
          %h1= "#{@conference.name} conference"
          %h2= format_days(@conference)
          %h3= "#{@conference.venue} - #{@conference.city}"

        %nav#global
          %ul
            %li= link_to 'Home', :root
            %li= link_to 'About', '/about'
            %li= link_to 'Speakers', speakers_path
            %li= link_to 'Sessions', sessions_path
            %li= link_to 'Schedule', schedule_path
            %li= link_to 'Registration', '/registration'
            %li= link_to 'Mobile', '/develop'
            %li= link_to 'Log Out', log_out_path if current_user

      .clear_fix
        = yield

      = javascript_include_tag "application", :debug => Rails.env.development?
      = yield :doctail            
            

app/views/layouts/application.html.haml
%html
  %head
    %meta{'http-equiv'=>"Content-Type", :content=>"text/html; charset=UTF-8"}
    %title= "#{@conference.name} conference"
    %meta{:name=>"title", :content=>"#{@conference.name} conference"}
    %meta{:name=>"keywords", :content=>""}
    %meta{:name=>"description", :content=>""}
    %meta{:name=>"copyright", :content=> "#{@conference.name} conference"}
    %meta{:name=>"revisit-after", :content=>"15 days"}

    %meta{:name=>"robots", :content=>"all"}
    = stylesheet_link_tag "application", :debug => Rails.env.development?
    = csrf_meta_tags
    = yield :dochead

  %body{class: body_style}
    .topbar
      .fill
        .container
          = link_to("#{@conference.name} conference", '#', class: 'brand')
        
          %ul.nav
            %li= link_to 'Home', :root
            %li= link_to 'Speakers', speakers_path
            %li= link_to 'Sessions', sessions_path
            %li= link_to 'Schedule', schedule_path
            %li= link_to 'Mobile', '/develop'
            - if current_user
              %li= link_to 'Log Out', log_out_path 

    .container
      = yield

      %footer
        %p
          = link_to 'Privacy Policy', '/privacy'
          |
          = link_to 'Terms And Conditions', '/toc'

    = javascript_include_tag "application", :debug => Rails.env.development?
    = yield :doctail 

app/views/layouts/west.html.haml
%html
  %head
    %meta{'http-equiv'=>"Content-Type", :content=>"text/html; charset=UTF-8"}
    %title= "#{@conference.name}"
    %meta{:name=>"title", :content=>"#{@conference.name}"}
    %meta{:name=>"keywords", :content=>""}
    %meta{:name=>"description", :content=>""}
    %meta{:name=>"copyright", :content=> "#{@conference.name}"}
    %meta{:name=>"revisit-after", :content=>"15 days"}

    %meta{:name=>"robots", :content=>"all"}
    = stylesheet_link_tag "application", :debug => Rails.env.development?
    = csrf_meta_tags
    = yield :dochead

  %body
    %header
      %hgroup
        %h1= "#{@conference.name} conference"
        %h2= format_days(@conference)
        %h3= "#{@conference.venue} - #{@conference.city}"
        
      %nav#global
        %ul
          %li= link_to 'Home', :root
          %li= link_to 'About', '/about'
          %li= link_to 'Speakers', speakers_path
          %li= link_to 'Sessions', sessions_path
          %li= link_to 'Schedule', schedule_path
          %li= link_to 'Registration', '/registration'
          %li= link_to 'Mobile', '/develop'
          %li= link_to 'Log Out', log_out_path if current_user

    .clear_fix
      = yield

    %footer.clear_fix
      %section
        %p 
          = link_to 'Privacy Policy', '/privacy'
          |
          = link_to 'Terms And Conditions', '/toc'

    = javascript_include_tag "application", :debug => Rails.env.development?
    = yield :doctail 